# Generated by Django 6.0.5 on 2026-06-03 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('ultimo_nome', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
                ('obito', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autores_adicionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['primeiro_nome', 'ultimo_nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_adicionadas', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='livros.categoria', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('publicado_at', models.DateField(verbose_name='Publicado Quando')),
                ('volume', models.CharField(blank=True, max_length=4, null=True)),
                ('edicao', models.CharField(blank=True, max_length=30, null=True, verbose_name='Edição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editoras_adicionadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_emprestimo', models.CharField(choices=[('longo', 'Longo'), ('medio', 'Médio'), ('curto', 'Curto'), ('unico', 'Único')], max_length=20, verbose_name='Tipo de Empréstimo')),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=14, unique=True)),
                ('paginas', models.CharField(max_length=4)),
                ('faixa_etaria', models.CharField(max_length=3)),
                ('endereco', models.CharField(max_length=30)),
                ('quantidade', models.CharField(max_length=4)),
                ('valor', models.FloatField(default=0.0, verbose_name='Valor do Livro (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros_adicionados', to=settings.AUTH_USER_MODEL)),
                ('autor', models.ManyToManyField(related_name='livros', to='livros.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros.categoria')),
                ('editora', models.ManyToManyField(related_name='livros', to='livros.editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
    ]
