# Generated by Django 6.0.4 on 2026-08-29 13:53

from django.db import migrations, models


def backfill_quantidade_disponivel(apps, schema_editor):
    Livro = apps.get_model('livros', 'Livro')
    Emprestimo = apps.get_model('emprestimos', 'Emprestimo')
    for livro in Livro.objects.all():
        total = 0
        try:
            total = int(livro.quantidade or 0)
        except (ValueError, TypeError):
            total = 0
        emprestados = (
            Emprestimo.objects
            .filter(livro=livro, devolvido_at__isnull=True)
            .count()
        )
        livro.quantidade_disponivel = max(total - emprestados, 0)
        livro.save(update_fields=['quantidade_disponivel'])


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=0, help_text='Exemplares disponíveis para empréstimo (diminui/sobe automaticamente).', verbose_name='Quantidade Disponível'),
        ),
        migrations.RunPython(backfill_quantidade_disponivel, migrations.RunPython.noop),
    ]
