# Generated by Django 6.0.5 on 2026-06-03 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enderecos_adicionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['pais', 'estado', 'cidade'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=40, unique=True)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('eh_ativo', models.BooleanField(default=True)),
                ('tipo_usuario', models.CharField(choices=[('aluno', 'Aluno'), ('funcionario', 'Funcionário'), ('convidado', 'Convidado')], default='convidado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_adicionados', to=settings.AUTH_USER_MODEL)),
                ('endereco', models.ManyToManyField(blank=True, related_name='usuarios', to='usuarios.endereco')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome_completo'],
            },
        ),
    ]
