# Generated by Django 6.0.5 on 2026-06-03 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_limite', models.DateField()),
                ('devolvido_at', models.DateField(blank=True, null=True)),
                ('multa_atraso', models.FloatField(default=0.0, editable=False)),
                ('multa_avaria', models.FloatField(default=0.0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_registrados', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='livros.livro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimo_ativo', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-created_at'],
            },
        ),
    ]
