# Generated by Django 6.0.4 on 2026-08-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
        ('usuarios', '0004_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='usuarios.usuario'),
        ),
    ]
